---
pr:
- master

name: Scheduled deletion of orphaned resources
schedules:
  - cron: '0 8 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  service_connection: dts-management-prod-intsvc

jobs:
  - job: OrphanResourceCleanup
    # Only run on master branch
#     condition: eq(variables.isMaster, true)
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: Bash@3
        displayName: 'Install resource-graph az extension'
        inputs:
          targetType: 'inline'
          script: |
            set -x
            az config set extension.use_dynamic_install=yes_prompt
            az extension add --name resource-graph
      - task: AzureKeyVault@1
        displayName: 'Get secrets from Keyvault'
        inputs:
          azureSubscription:  "DTS-CFTPTL-INTSVC"
          keyVaultName:   "cftptl-intsvc"
          secretsFilter: 'orphaned-resources-slack-webhook'
      - task: AzureCLI@2
        displayName: 'Deleting orphaned resources in Azure'
        inputs:
          scriptType: bash
          scriptPath: scripts/orphan-cleanup.sh
          azureSubscription: ${{ variables.service_connection }}
          arguments: $(orphaned-resources-slack-webhook) dtspo-orphaned-resource-cleanup