---
name: Scheduled deletion of orphaned resources
schedules:
  - cron: '0 8 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'
trigger: none

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  service_connection: DCD-CFT-Sandbox

jobs:
  - job: OrphanResourceCleanup
    # Only run on master branch
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get secrets from Keyvault'
        inputs:
          azureSubscription:  "DTS-CFTPTL-INTSVC"
          keyVaultName:   "cftptl-intsvc"
          secretsFilter: 'orphaned-resources-slack-webhook'
      - task: AzureCLI@2
        displayName: 'Dry Run delete orphaned resources in Azure'
        condition: eq(variables.isMaster, false)
        inputs:
          scriptType: bash
          scriptPath: scripts/orphan-cleanup.sh
          azureSubscription: ${{ variables.service_connection }}
          arguments: '-m dry-run' $(orphaned-resources-slack-webhook) dtspo-orphaned-resource-cleanup
      - task: AzureCLI@2
        displayName: 'Deleting orphaned resources in Azure'
        condition: eq(variables.isMaster, true)
        inputs:
          scriptType: bash
          scriptPath: scripts/orphan-cleanup.sh
          azureSubscription: ${{ variables.service_connection }}
          arguments: $(orphaned-resources-slack-webhook) dtspo-orphaned-resource-cleanup
