---
name: Scheduled deletion of orphaned resources
schedules:
  - cron: '0 8 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'
trigger: none

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  service_connection: DCD-CFT-Sandbox

jobs:
  - job: OrphanResourceCleanup
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get secrets from Keyvault'
        inputs:
          azureSubscription:  "DTS-CFTPTL-INTSVC"
          keyVaultName:   "cftptl-intsvc"
          secretsFilter: 'orphaned-resources-slack-webhook'
      - task: AzureCLI@2
        # Run dry run if not master branch
        displayName: 'Deleting orphaned resources in Azure'
        inputs:
          scriptType: bash
          azureSubscription: ${{ variables.service_connection }}
          scriptLocation: 'inlineScript'
          ${{ if eq(variables.isMaster, false) }}:
            inlineScript: './scripts/orphan-cleanup.sh -m dry-run $(orphaned-resources-slack-webhook) dtspo-orphaned-resource-cleanup'
          ${{ else }}:
            inlineScript: './scripts/orphan-cleanup.sh $(orphaned-resources-slack-webhook) dtspo-orphaned-resource-cleanup'