name: orphaned-resource-cleanup

on:
  workflow_dispatch:
   inputs:
      dryRunEnabled:
        description: 'Enable Dry-Run Mode'
        required: true
        default: true
        type: boolean
  #  schedule:
  #    - cron: '0 19 * * *' # Every day at 8pm BST

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: ${{ inputs.dryRunEnabled == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: a1f7ea99-63f1-4b56-8813-a4b0ab781cf2 # DTSPO Orphaned Resource Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
      - name: Get slack webhook secret
        id: slack-webhook
        run: |
          secrets_get=(orphaned-resources-slack-webhook)
          for secret_get in ${secrets_get[@]}
          do
            value=$(az keyvault secret show --name $secret_get --vault-name cftptl-intsvc --query value --output tsv)
            echo "::add-mask::$value"
            echo "$secret_get=$value" >> $GITHUB_OUTPUT
          done
      - name: Dry Run orphaned resources in Azure
        run: ./scripts/orphan-cleanup.sh -m dry-run ${{ steps.azure-keyvault-secrets.outputs.orphaned-resources-slack-webhook }} dtspo-orphaned-resource-cleanup
  
  live:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: ${{ inputs.dryRunEnabled == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: a1f7ea99-63f1-4b56-8813-a4b0ab781cf2 # DTSPO Orphaned Resource Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
      - name: Get slack webhook secret
        id: slack-webhook
        run: |
          secrets_get=(orphaned-resources-slack-webhook)
          for secret_get in ${secrets_get[@]}
          do
            value=$(az keyvault secret show --name $secret_get --vault-name cftptl-intsvc --query value --output tsv)
            echo "::add-mask::$value"
            echo "$secret_get=$value" >> $GITHUB_OUTPUT
          done
      - name: Dry Run orphaned resources in Azure
        run: ./scripts/orphan-cleanup.sh -m dry-run ${{ steps.azure-keyvault-secrets.outputs.orphaned-resources-slack-webhook }} dtspo-orphaned-resource-cleanup