name: orphaned-resource-cleanup

on:
  workflow_dispatch:
    inputs:
      dryRunEnabled:
        description: 'Enable Dry-Run Mode'
        required: true
        default: false
        type: boolean
  schedule:
    - cron: '0 9 * * *' # Every day at 8pm BST

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: ${{ inputs.dryRunEnabled == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: c670b53f-74bc-4fa8-82c6-5577e8600d2a # DTSPO Orphaned Resource Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Dry Run orphaned resources in Azure
        run: ./scripts/orphan-cleanup.sh -m dry-run ${{ steps.slack-webhook.outputs.orphaned-resources-slack-webhook }} dtspo-orphaned-resource-cleanup
      - name: Output deletion objects
        run: |
            cat ./status/deletionStatus.json

  live:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: ${{ inputs.dryRunEnabled == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: c670b53f-74bc-4fa8-82c6-5577e8600d2a # DTSPO Orphaned Resource Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Delete orphaned resources in Azure
        run: ./scripts/orphan-cleanup.sh
      - name: Commit deletion status json file
        continue-on-error: true
        run: |
          git config user.name hmcts-platform-operations
          git config user.email github-platform-operations@hmcts.net
          git stash
          git checkout failedDeletionStatus
          git stash pop
          git add ./status
          git commit -m "Automated - save failed deletions to json file"
          git push --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
